// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwrssvydrxjtbujrvkcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cnNzdnlkcnhqdGJ1anJ2a2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjkxNjIsImV4cCI6MjA3NDY0NTE2Mn0.ExzN_8SAqg5w2h-bu-HjZBuvwQPMWLUNvtd8inKGTV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});